# Instrutor do workshop

Osvaldo Luiz dos Santos Pereira


## Formação

* graduação em bacharelado em física pela Unicamp
* mestrado em física pela Unicamp
* MBA em big data em analytics pela USP-Esalq (em andamento)
* Doutorado em física pela UFRJ (em andamento)


## Experiência profissional

* Itaú Unibanco: analista de Pesquisa e desenvolvimento (P&D)
* Itaú Unibanco: analista de risco de crédito
* Kroton: consultor de produção de conteúdo
* Kroton: criador de conteúdo (escritor)
* Itaguaí Construções Navais: Cientista de Dados sr. (Especialista)
* C&T: Especialista senior em ciência de dados
* Hospital Sírio Libanês: Consultor senior especialista em ciência de dados
* Fundador e CTO da sciencedata.ai
* Coordenador de programa trainee Sciencedata.ai
* Sua Música: Head of BI
* Pesquisador convidado pela UFRJ (Física Teórica)

## Áreas de interesse (pesquisa)

* Física teórica
* computação e informação quântica
* machine learning clássico
* machine learning quântico
* deep learning
* deep learning geométrico
* Econofísica

## Produção acadêmica

* Livro de eletromagnetismo clássico (Editora Kroton)
* Livro de mecânica geral (Editora Kroton)
* Artigos técnicos em revistas indexadas em inglês
* Artigos não técnicos em revistas digitais
* Lecture notes (Português e inglês) em diversos assuntos técnicos


## Consultorias em empresas

* Samsung
* Olist
* Sky
* Itaú-Unibanco
* CeA
* Cimed
* IBM
* Citibank
* Nestlé
* Bradesco
* Centauro
* FGC
* FIESC
* Equatorial
* Green Yellow
* Lendico
* Aerocivil
* Reciclare
* Pipefy
* Corteva (Grupo Dupont)
* Evolve
* Sysmap
* Digisystem
* TechforIT
* Alstra
* Atos
* ImperioIT
* Cognitivo
* Wayon
* KLB
* Cognitivo

# Resumo da aula

* Funções
* Números complexos
* Recursão
* Lambdas
* arrays

# Funções

## Sintaxe e exemplos simples

In [ ]:
print('Hello World!')

In [ ]:
3+5

In [ ]:
def hello_world():
    print('Hello World!')

In [ ]:
hello_world()

In [ ]:
def x_ao_quadrado(x):
    return x * x

In [ ]:
x_ao_quadrado(2)

In [ ]:
x_ao_quadrado(3)

In [ ]:
def f(x):
    return x**3 + x**2

In [ ]:
f(2)

In [ ]:
2**3 + 2**2

In [ ]:
def func(x, y, z):
    print('x: ', x)
    print('y: ', y)
    print('z: ', z)

    return (x * y)**z

In [ ]:
func(1, 3, 4)

In [ ]:
func(x = 1, y = 3, z = 0)

In [ ]:
import numpy as np

def raiz(a):
    if a < 0:
        return 'raíz complexa'
    else:
        return np.sqrt(a)

raiz(-4)

In [ ]:
def sucessor(n):
    n = n + 1
    print(n)

sucessor(5)

In [ ]:
sucessor(6)

In [ ]:
def sucessork(n,k):
    n = n + k
    print(n)
    
sucessork(5,2)

In [ ]:
4%2

In [ ]:
5%2

In [ ]:
6%2

In [ ]:
def par_ou_nao(valor):
    if (type(valor) != int):
        print('Não é inteiro:', valor)
    elif (valor % 2 == 0):
        print('É um número par: ', valor)
    elif (valor % 2 == 1):
        print('É um número ímpar: ', valor)

par_ou_nao(valor = 5)

In [ ]:
211%2

## Calcula raízes do segundo grau

Neste exemplo vamos criar um solucionador de equações do segundo grau

\begin{equation}
\nonumber ax^2 + bx + c = 0
\end{equation}

Lembrando que devemos ter a condição de que $a \neq 0$ para que a equação seja do
segundo grau. A solução para esta equação é dada por

\begin{equation}
\nonumber x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
\end{equation}

Lembrando que para que as raízes sejam reais é necessário que o termo dentro da raiz quadrada seja sempre maior ou igual a zero. Este termo dentro da raíz quadrada é conhecido por discriminante e representado pela letra grega maiúscula delta $\Delta$.

\begin{equation}
\nonumber \Delta = b^2 - 4ac
\end{equation}

O x do vértice $(x_V)$ é dado pela relação

\[x_V = - \frac{b}{2a}\]

O y do vértice é dado pelo valor da função quadrática calculada no valor do x do vértice, ou seja

\[y_V = f(x_V) = ax_V^2 + bx_V + c\]

In [ ]:
from sympy import init_printing
from sympy import *
import sympy as sym
import numpy as np
import pandas as pd

from sympy.abc import a, e, k, n, r, t, x, y, z, T, Z
from sympy.abc import beta, omega, tau

init_printing()
sym.init_printing() 

In [ ]:
x = sym.Symbol('x')
y = sym.Symbol('y')

In [ ]:
(a+b)**2

In [ ]:
a,b = 1,2

(a+b)**2

In [ ]:
sym.expand((x + y)**2)

In [ ]:
(x + x * y) / x

In [ ]:
sym.simplify((x + x * y) / x)

In [ ]:
x + x * y

In [ ]:
sym.factor((x + x * y))

In [ ]:
eq1 = x**2 + 2*x + 1

eq1

In [ ]:
sym.factor(eq1)

## Definir uma função para cálculo de equação do segundo grau

In [ ]:
x = sym.Symbol('x')
y = sym.Symbol('y')
a = sym.Symbol('a')
b = sym.Symbol('b')
c = sym.Symbol('c')

In [ ]:
a*x**2 + b*x + c*x**0

In [ ]:
discriminante = b**2 - 4*a*c

discriminante

In [2]:
a,b,c = 1,2,3

discriminante = b**2 - 4*a*c

discriminante

-8

In [3]:
def discriminante(a,b,c):
    disc = b**2 - 4*a*c
    return disc

discriminante(1,2,3)

-8

In [6]:
np.sqrt(4)

2.0

In [7]:
np.sqrt(9)

3.0

In [8]:
np.sqrt(-4)

<ipython-input-8-7d3c0d738928>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-4)


nan

In [9]:
pow(-4,1/2)

(1.2246467991473532e-16+2j)

In [10]:
j

NameError: name 'j' is not defined

In [ ]:
# a = parte real do número complexo
# b =  parte imaginária do número complexo
# j = raiz imaginária de -1
z = a + bj

In [12]:
z = 1 + 1j
z

(1+1j)

In [5]:
import numpy as np

def equacao_segundo(a,b,c):
    disc = b**2 - 4*a*c
    x1 = (-b + np.sqrt(disc))/(2*a)
    x2 = (-b - np.sqrt(disc))/(2*a)
    
    print('x1 =', x1)
    print('x2 =', x2)
    
equacao_segundo(1,2,3)  

x1 = nan
x2 = nan


<ipython-input-5-f6f6b377d580>:5: RuntimeWarning: invalid value encountered in sqrt
  x1 = (-b + np.sqrt(disc))/(2*a)
<ipython-input-5-f6f6b377d580>:6: RuntimeWarning: invalid value encountered in sqrt
  x2 = (-b - np.sqrt(disc))/(2*a)


In [14]:
def equacao_segundo(a,b,c):
    disc = b**2 - 4*a*c
    x1 = (-b + pow(disc,1/2))/(2*a)
    x2 = (-b - pow(disc,1/2))/(2*a)
    
    print('x1 =', x1)
    print('x2 =', x2)
    
equacao_segundo(1,2,3)  

x1 = (-0.9999999999999999+1.4142135623730951j)
x2 = (-1-1.4142135623730951j)


In [15]:
def eq_solver(a,b,c):
    # 
    discriminante = b**2 - 4*a*c
    if discriminante < 0: 
        return 'sem raízes reais'
    else:
        print('Discriminante = ', discriminante)
        # 
        x1 = (-b + np.sqrt(discriminante))/(2*a)
        x2 = (-b - np.sqrt(discriminante))/(2*a)

        print('x1 =', x1)
        print('x2 =', x2)

        return x1, x2

In [16]:
eq_solver(a = 1,b = 2,c = 1)

Discriminante =  0
x1 = -1.0
x2 = -1.0


(-1.0, -1.0)

In [17]:
eq_solver(a = 1,b = 2,c = 3)

'sem raízes reais'

# Números complexos

In [18]:
import cmath, math

In [19]:
z = 1 + 1j

z

(1+1j)

In [20]:
z = 2 + 3j
z

(2+3j)

In [21]:
z = complex(2,3)
z

(2+3j)

In [22]:
np.sqrt(z)

(1.6741492280355401+0.8959774761298381j)

In [23]:
z

(2+3j)

In [24]:
abs(-4)

4

In [25]:
abs(z)

3.605551275463989

In [26]:
np.sqrt(2**2 + 3**2)

3.605551275463989

In [27]:
z.real

2.0

In [28]:
z.imag

3.0

In [29]:
z

(2+3j)

In [30]:
z.conjugate()

(2-3j)

In [31]:
z = 1 - 5j
z

(1-5j)

In [32]:
z.conjugate()

(1+5j)

In [33]:
pow(z,2)

(-24-10j)

In [34]:
pow(4,2)

16

In [ ]:
z = a + bj
z**2 = ?

(a + bj)**2 = a**2 + 2 a bj + (bj)**2 
= a**2 + 2 a bj + b**2 j**2
= a**2 + 2 a bj + b**2 (-1)

In [35]:
z = 1 + 1j
z

(1+1j)

In [36]:
pow(z,2)

2j

In [37]:
(1+1j)**2

2j

In [39]:
1**2 + 2*1*1j + (1j)**2

2j

In [41]:
z

(1+1j)

In [40]:
pow(z,1/2)

(1.0986841134678098+0.45508986056222733j)

In [ ]:
j**2 = -1

In [ ]:
0 + 1j

In [45]:
6.123233995736766e-17

6.123233995736766e-17

In [47]:
10**(-17) == 0

False

In [42]:
pow(-1,1/2)

(6.123233995736766e-17+1j)

## Mais exemplos

In [48]:
def comparador(x , y):
    if (x > y):
        print(x, 'maior que ', y)
    elif (x < y):
        print(x, 'menor que ', y)
    else:
        print(x, 'igual a ', y)
        
comparador(1,1)
comparador(10,1)
comparador(1,10)

1 igual a  1
10 maior que  1
1 menor que  10


In [49]:
def compara_string(texto_1, texto_2):
    if (texto_1 == texto_2):
        print('Textos iguais! (', texto_1, ')')
    else:
        print('Os textos são diferentes!', '(', texto_1, ')', ' diferente de ', '(', texto_2, ')')

compara_string(texto_1 = 'aaa', texto_2 = 'aaa')
compara_string(texto_1 = 'aaa', texto_2 = 'bb')

Textos iguais! ( aaa )
Os textos são diferentes! ( aaa )  diferente de  ( bb )


# Recursão

## Método para cálculo de fatorial usando iteração

In [52]:
def f(n):
    n = n + 1
    return n

f(5)

6

In [53]:
f(f(5))

7

In [ ]:
fat(n) = n*(n-1)*(n-2)*...*3*2*1

In [61]:
5*4*3*2*1

120

## Exemplo do que não devemos fazer

In [63]:
fat = 1
n = 5

for i in range(1,n+1):
    fat = fat*i
    #print (fat)

fat

120

In [64]:
def fatorial_it(n) :
    k = 1
    for i in range(1,n+1):
        k = k * i
    return k

n = int(input('digite um número para n: '))
print(n,'! = ',fatorial_it(n))

digite um número para n: 5
5 ! =  120


## Fatorial

In [69]:
def fatorial_1(n):
        x = n-1
        fat = fatorial_1(x)
        return n*fat
    
fatorial_1(5)

RecursionError: maximum recursion depth exceeded

In [70]:
def fatorial_1(n):
    if n <= 1:
        return 1
    else: 
        x = n-1
        fat = fatorial_1(x)
        return n*fat

n = int(input('digite um valor para n:'))
print(fatorial_1(n))

digite um valor para n:5
120


In [71]:
def fatorial_2(n):
    if n <= 1:
        return 1
    else: 
        return n * fatorial_2(n-1)

n = int(input('digite um valor para n: '))
print(fatorial_2(n))

digite um valor para n: 5
120


In [72]:
def fatorial_3(x):
    fat = 1
    for i in range(1, x + 1):
        fat = fat * i
    return fat

n = int(input('digite um valor para n: '))
print(fatorial_3(n))

digite um valor para n: 5
120


## Simples exemplo de recursão (soma acumulada)

Python também aceita recursão de função, o que significa que uma função definida pode chamar a si mesma. A recursão é um conceito matemático e de programação comum. Isso significa que uma função chama a si mesma. O desenvolvedor deve ter muito cuidado com a recursão, pois pode ser muito fácil escrever uma função que nunca termina, ou que usa uma quantidade excessiva de memória ou potência do processador. No entanto, quando escrito corretamente, a recursão pode ser uma abordagem de programação muito eficiente e matematicamente elegante. Neste exemplo, recursao() é uma função que definimos para chamar a si mesma. Usamos a variável k como os dados, que diminui (-1) toda vez que recursamos. A recursão termina quando for igual a 0.

In [73]:
def recursao(k):
    if(k > 0):
        acumulado = k + recursao(k - 1)
        print(acumulado)
    else:
        acumulado = 0
    return acumulado

recursao(6)

1
3
6
10
15
21


21

In [74]:
recursao(0)

0

In [75]:
recursao(1)

1


1

In [76]:
recursao(2)

1
3


3

## Calcula o mdc entre x e y

In [77]:
def mdc1(x, y):
    while (y != 0):
        (x, y) = (y, x % y)
    return x

mdc1(120, 25)

5

In [78]:
120/25

4.8

In [79]:
120/5

24.0

In [80]:
25/5

5.0

In [85]:
a = 1
b = 2
c = 3

a = b
b = a
c = b

c

2

In [86]:
def mdc2(x, y):
    while (y != 0):
        r = x % y
        x = y
        y = r
    return x

mdc2(120, 25)

5

## Calcula o mmc entre x e y

In [87]:
def mmc1(x, y):
    resultado = 1
    while (resultado % x != 0) or (resultado % y != 0):
        resultado = resultado + 1
    return resultado

mmc1(150, 125)

750

In [88]:
def mmc2(x, y):
    resultado = x
    while resultado % y != 0:
        resultado = resultado + x
    return resultado

mmc2(150, 125)

750

In [89]:
def mmc3(x, y):
    resultado = max(x, y)
    while resultado % min(x, y) != 0:
        resultado = resultado + max(x, y)
    return resultado

mmc3(150, 125)

750

In [90]:
def mmc4(x, y):
    return int((x * y) / mdc2(x, y))

mmc4(150, 125)

750

In [91]:
def mmc5(x, y):
    if (x < y):
        (x, y) = (y, x)
    resultado = x
    while resultado % y != 0:
        resultado = resultado + x
    return resultado

mmc5(150, 125)

750

## Função reverso de um número

In [94]:
def reverso(x):
    rev = 0
    while x >0:
        rest = x % 10
        x = x // 10
        rev = rev * 10 + rest
    return rev

n = int(input())
print(reverso(n))

63
36


## Soma dos n primeiro naturais

In [ ]:
1+2+3+4+5+...+100

In [105]:
soma = 0
n = 10

for i in range(0,n):
    i = i + 1
    soma = soma + i
    print(i)
    
soma

1
2
3
4
5
6
7
8
9
10


55

In [107]:
def soma_n1(n):
    soma = 0

    for i in range(0,n):
        i = i + 1
        soma = soma + i
    
    return soma

soma_n1(100)

5050

In [101]:
def soma_n(n):
    total, k = 0, 1
    while k <= n:
        total, k = total + k, k + 1
    return total

soma_n(100)

5050

In [ ]:
def fatorial_2(n):
    if n <= 1:
        return 1
    else: 
        return n * fatorial_2(n-1)

In [124]:
soma

55

In [126]:
def somanrec(n):
    if n <= 1:
        return 1
    else:
        return n + somanrec(n-1)

somanrec(100)

5050

## Soma dos n primeiros potências de 2 dos números naturais

In [ ]:
1^k+2^k+3^k+4^k+5^k+...+n^k

In [127]:
def soma_nk(n,p):
    total, k = 0, 1
    while k <= n:
        total, k = total + k**p, k + 1
    return total

soma_nk(3,2)

14

In [128]:
1**2 + 2**2 + 3**2

14

In [129]:
soma_nk(3,3)

36

In [130]:
1**3 + 2**3 + 3**3

36

In [456]:
import time

start = time.time()
soma_nk(1000,3)
end = time.time()
print(end - start)

0.0009980201721191406


In [139]:
def soma_nk(n,p):
    if n <= 1:
        return 1
    else:
        return n**p + soma_nk(n-1,p)

soma_nk(3,2)

14

## Sequência de Fibonacci

A sequência de Fibonacci foi descoberta por Leonardo de Pisa em 1202 ao investigar a já famosa
razão de ouro $(\varphi)$. Neste trabalho ele descobriu a seguinte sequência de números:

\begin{equation}
\nonumber 1,\;1,\;2,\;3,\;5,\;8,\;13,\;21,\;34,\;55,\;89,\;144,\;\ldots 
\end{equation}

A sequência acima é gerada recursivamente pela sequinte equação funcional.

\begin{equation}
\nonumber F(n+2) = F(n + 1) + F(n).
\end{equation}

Obs.: A sequência de Fibonacci é usualmente iniciada com n = 1 e as condições de que F(1) = 1 
e que F(2) = 1, porém muitas pessoas iniciam a sequência com n = 0 e que F(0) = 1 e que F(1) = 1.
Nenhum dos dois modos está errado. Essa divergência acontece devido ao interminável debate se o
número 0 faz parte ou não dos números naturais.

In [141]:
def fibo(n):
    if n <= 1:
        return 1
    else:
        return(fibo(n-1) + fibo(n-2))
n = int(input('digite um número para n: '))
if n <= 0:
    print('Insira um número inteiro maior que zero.')
else:
    print('Sequência de Fibonacci para n = ', n)
    for i in range(n):
        print(fibo(i))

digite um número para n: 10
Sequência de Fibonacci para n =  10
1
1
2
3
5
8
13
21
34
55


Sequência dos primeiros números naturais

\[S(n) = 1 + 2 + 3 + ... + n = \sum_{k=1}^{n} k \ \to \ f(k) = k\]

Sequência das potências k dos primeiros naturais

\[S_k(n) = 1^k + 2^k + 3^k + ... + n^k = \sum_{a=1}^{n} a^k \ \to \ f(k) = a^k\]

Função geradora da sequência de Fibonnaci

\[f(n+2) = f(n+1) + f(n)\]

In [ ]:
1 + 2 + 3 + ... + n
1**k + 2**k + ... + n**k

In [143]:
def f(n):
    f = n
    return f
    
f(10)

10

In [156]:
def f(n):
    f = n
    return f

def seq(n):
    if n <=1:
        return 1
    else:
        soma2 = 0
        for x in range(0,n+1):
            soma2 = soma2 + f(x)
    return soma2
    
seq(100)

5050

In [159]:
def f(n,k):
    f = n**k
    return f

def seq(n,k):
    if n <=1:
        return 1
    else:
        soma = 0
        for x in range(0,n+1):
            soma = soma + f(x,k)
    return soma
    
seq(3,3)

36

# Lambdas

A expressão lambda é mais útil como um atalho para def, quando você precisa inserir pequenos pedaços de código executável em locais onde as declarações são sintaticamente ilegais.

## Comparando lambda vs função

In [160]:
def f(x, y, z):
    return x + y + z

f(2, 3, 4)

9

In [161]:
f = lambda x, y, z: x + y + z

f(2, 3, 4)

9

O trecho de código abaixo constrói uma lista de três funções incorporando expressões lambda dentro de um literal de lista; um def não funcionará dentro de uma lista literal, porque é uma declaração, não uma expressão. A codificação def equivalente exigiria nomes de funções temporários (que poderiam colidir com outros nomes) e definições de funções fora do contexto de uso pretendido (que pode estar distante):

In [162]:
L = [lambda x: x ** 2, lambda x: x ** 3, lambda x: x ** 4]

for f in L:
    print(f(2))

4
8
16


In [164]:
L

[<function __main__.<lambda>(x)>,
 <function __main__.<lambda>(x)>,
 <function __main__.<lambda>(x)>]

In [165]:
L[0]

<function __main__.<lambda>(x)>

In [166]:
L[1]

<function __main__.<lambda>(x)>

In [167]:
L[2]

<function __main__.<lambda>(x)>

In [168]:
# Retorna o valor da primeira lambda tendo como argumento o número dentro dos ()
L[0](2)

4

In [169]:
# Retorna o valor da segunda lambda tendo como argumento o número dentro dos ()
L[1](2)

8

In [170]:
# Retorna o valor da terceira lambda tendo como argumento o número dentro dos ()
L[2](2)

16

In [172]:
def f1(x):
    return x ** 2

def f2(x):
    return x ** 3

def f3(x):
    return x ** 4

R = [f1, f2, f3]

for f in R:
    print(f(2))

4
8
16


In [174]:
# Retorna o valor da primeira função tendo como argumento o número dentro dos ()
R[0](2)

4

In [175]:
# Retorna o valor da segunda função tendo como argumento o número dentro dos ()
R[1](2)

8

In [176]:
# Retorna o valor da terceira função tendo como argumento o número dentro dos ()
R[2](2)

16

# Funções aninhadas

## Exemplos simples - soma dos n primeiros naturais

In [183]:
total = 0 
k = 1

n = int(input("Digite um número inteiro positivo:"))

while k <= n:
    total = total + k
    k = k + 1
    
print(total)

Digite um número inteiro positivo:100
5050


In [187]:
def f(n,k):
    f = n**k
    return f

def seq(n,k):
    if n <=1:
        return 1
    else:
        soma = 0
        for x in range(0,n+1):
            soma = soma + f(x,k)
    return soma
    
seq(100,1)

5050

In [184]:
def soma(n):
    total = 0 
    k = 1
    while k <= n:
        total = total + k
        k = k + 1
    return total

soma(100)

5050

In [194]:
def soma(n, term):
    total = 0
    k = 1
    while k <= n:
        total = total + term(k)
        k = k + 1
    return total

def f(x):
    return x

soma(100, f)

5050

In [226]:
def g(n, p, a, f):
    total = 0
    k = 1
    for k in range(0,n+1):
        total = total + f(k,p,a)
        k = k + 1
    return total

def f(x,p,a):
    return x**p + a

g(100, 1, 0, f)

5050

# Arrays

In [227]:
import numpy as np
import pandas as pd

## Definindo matriz

In [233]:
A = [1,2,3]

A = np.array(A)

A

array([1, 2, 3])

In [234]:
np.shape(A)

(3,)

In [235]:
A = [[1],[2],[3]]

A = np.array(A)

A

array([[1],
       [2],
       [3]])

In [236]:
np.shape(A)

(3, 1)

In [238]:
# definindo uma matriz 2x3 chamada A
A = [[1, 4, 5], 
    [-5, 8, 9]]

A = np.array(A)

A

array([[ 1,  4,  5],
       [-5,  8,  9]])

In [239]:
np.shape(A)

(2, 3)

In [240]:
A = ['a', 'b', 'c', 'd']

In [241]:
A[0]

'a'

In [242]:
A[1]

'b'

In [243]:
A = [['a'],[ 'b'], ['c'], ['d']]

A = np.array(A)

A

array([['a'],
       ['b'],
       ['c'],
       ['d']], dtype='<U1')

In [244]:
np.shape(A)

(4, 1)

In [245]:
A[0]

array(['a'], dtype='<U1')

In [246]:
A[0][0]

'a'

In [285]:
A = [['a1', 'a2', 'a3', 'a4'],
     [ 'b1', 'b2', 'b3', 'b4'], 
     ['c1', 'c2', 'c3', 'c4'], 
     ['d1', 'd2', 'd3', 'd4']
    ]

A = np.array(A)

A

array([['a1', 'a2', 'a3', 'a4'],
       ['b1', 'b2', 'b3', 'b4'],
       ['c1', 'c2', 'c3', 'c4'],
       ['d1', 'd2', 'd3', 'd4']], dtype='<U2')

In [248]:
np.shape(A)

(4, 4)

In [249]:
# acessamos a primeira linha da matriz A(4x4)
A[0]

array(['a1', 'a2', 'a3', 'a4'], dtype='<U2')

In [250]:
# acessamos a segunda linha da matriz A(4x4)
A[1]

array(['b1', 'b2', 'b3', 'b4'], dtype='<U2')

In [256]:
# acessando a segunda coluna da matriz A(4x4)
A[:,1]

array(['a2', 'b2', 'c2', 'd2'], dtype='<U2')

In [266]:
A[2,:2]

array(['c1', 'c2'], dtype='<U2')

In [272]:
A[1:,0]

array(['b1', 'c1', 'd1'], dtype='<U2')

In [273]:
A[0:,0]

array(['a1', 'b1', 'c1', 'd1'], dtype='<U2')

In [274]:
A[2:,0]

array(['c1', 'd1'], dtype='<U2')

In [275]:
A[2:,1]

array(['c2', 'd2'], dtype='<U2')

In [278]:
v = A[2:,1]

np.shape(v)

(2,)

In [281]:
v[0]

'c2'

In [280]:
v[1]

'd2'

## Entradas da matriz

Em geral representamos uma matriz por uma letra maiúscula qualquer, e seus elementos pelos sub índices, em geral utilizamos letras romandas (m,n,p,q,i,j,k,l) para designar as linhas e colunas de uma matriz.

\[A_{ij} = \begin{pmatrix} 
a_{11} & a_{12} \\ 
a_{21} & a_{22}
\end{pmatrix}\]

Por exemplo, o termo (11) da matriz é o termo $A_{11} = a_{11}$, o termo da primeira linha, e segunda coluna é o termo $A_{12} = a_{12}$. No Python, os contadores iniciam do zero por default, enquanto que em matemática, é comum utilizarmos o contador a partir de 1. Tomar cuidado com este tipo de detalhe.

In [286]:
A

array([['a1', 'a2', 'a3', 'a4'],
       ['b1', 'b2', 'b3', 'b4'],
       ['c1', 'c2', 'c3', 'c4'],
       ['d1', 'd2', 'd3', 'd4']], dtype='<U2')

In [287]:
# verificando componentes da matriz A
A[1][2]

'b3'

In [288]:
# definir uma matriz de 3 linhas e 1 coluna
B = [[1],[2],[3]]

B = np.array(B)

B

array([[1],
       [2],
       [3]])

In [289]:
np.shape(B)

(3, 1)

In [292]:
# definir uma matriz de 1 linha e 3 colunas
C = [[1,2,3]]

C = np.array(C)

C

array([[1, 2, 3]])

In [293]:
np.shape(C)

(1, 3)

In [ ]:
# [] = lista == vetor
# [[]] = lista de lista == matriz
# [[[]]] = lista de lista de lista == tensor

In [297]:
v = [1,2,3]

v = np.array(v)

v[0]

1

In [298]:
np.shape(v)

(3,)

In [303]:
A = [[1,2,3] # --> primeira coluna
    ]

A = np.array(A)

A

array([[1, 2, 3]])

In [304]:
A = [[1,2,3], # --> primeira linha
     [4,5,6], # --> segunda linha
     [7,8,9]  # --> terceira linha
    ]

A = np.array(A)

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [299]:
np.shape(A)

(1, 3)

In [305]:
A[1][1]

5

In [306]:
A[2][1]

8

In [300]:
T = [[[1,2,3]]]

T = np.array(T)

T

array([[[1, 2, 3]]])

In [301]:
np.shape(T)

(1, 1, 3)

In [283]:
# redefinindo componentes da matriz B
B[1][2] = 3

B[1][2]

'3'

## Soma de matrizes

Para somarmos duas ou mais matrizes, estas devem ter o mesmo número de linhas e de colunas, caso contrário, esta operação não funciona. Então, por exemplo se tivermos uma matriz $A(3x2)$, podemos somá-la à outra matriz $B(3x2)$, e esta soma é realizada termo a termo, ou seja, somamos da seguinte forma

\[C_{ij} = A_{ij} + B_{ij}\]

In [309]:
# definindo matriz X 3x3
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

X = np.array(X)

# definindo matriz Y 3x3
Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

Y = np.array(Y)

Z = X + Y

Z

array([[17, 15,  4],
       [10, 12,  9],
       [11, 13, 18]])

In [311]:
X

array([[12,  7,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [312]:
Y

array([[5, 8, 1],
       [6, 7, 3],
       [4, 5, 9]])

In [310]:
X[0][0]

12

In [313]:
Y[0][0]

5

In [314]:
z00 = X[0][0] + Y[0][0]

z00

17

In [316]:
Z

array([[17, 15,  4],
       [10, 12,  9],
       [11, 13, 18]])

In [315]:
Z[0][0]

17

## Exemplo de soma que não dá certo

Neste exemplo, vamos somar duas matrizes com diferentes quantidades de linhas e colunas, e vamos ver que esta operação resulta em erro

In [317]:
X = [[1,2],[3,4]]

X = np.array(X)

X

array([[1, 2],
       [3, 4]])

In [318]:
Y = [[1,2,3,4]]

Y = np.array(Y)

Y

array([[1, 2, 3, 4]])

In [319]:
Z = X + Y

ValueError: operands could not be broadcast together with shapes (2,2) (1,4) 

## Exemplos de geração de matrizes

In [322]:
# definindo matriz nula/inicializando uma matriz com entradas igual a 0
Z = np.zeros((3,3))

Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [326]:
I = np.identity(3)

I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Matriz inversa

A matriz inversa só existe no caso de matrizes quadradas que não são singulares. Uma matriz não singular é definida como uma matriz qualquer que tenha o valor do determinante diferente de zero. Em outras palavras, a matriz inversa de uma matriz qualquer só existe no caso do determinante ser não nulo. Como propriedade de matrizes não singulares quadradas, tem-se que

\[A . A^{-1} = A^{-1} . A = I\]

sendo $A$ uma matriz quadrada nxn, $A^{-1}$ a matriz inversa de $A$, e $I$ a matriz inversa de I.

In [327]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

X = np.array(X)

X

array([[12,  7,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [330]:
det_X = np.linalg.det(X)

det_X

-2.9999999999999982

In [331]:
inv_X = np.linalg.inv(X)

inv_X

array([[  1.        ,  13.        ,  -9.        ],
       [ -2.        , -29.        ,  20.        ],
       [  1.        ,  15.66666667, -10.66666667]])

In [357]:
np.matmul(X,inv_X)

array([[ 1.00000000e+00, -7.10542736e-15,  1.95399252e-14],
       [ 0.00000000e+00,  1.00000000e+00, -3.55271368e-15],
       [-4.44089210e-16, -1.42108547e-14,  1.00000000e+00]])

In [358]:
np.matmul(inv_X,X)

array([[ 1.00000000e+00,  0.00000000e+00,  1.42108547e-14],
       [ 2.48689958e-14,  1.00000000e+00,  3.55271368e-15],
       [-1.77635684e-15,  0.00000000e+00,  1.00000000e+00]])

In [333]:
3*4 == 4*3

True

## Definindo matrizes usando loop

In [335]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

X = np.array(X)

# definindo matriz Y 3x3
Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

Y = np.array(Y)

# definindo uma nova matriz somando duas matrizes
# utilizando um loop for
# iterando nas linhas
for i in range(len(X)):
    # iterando nas colunas
    for j in range(len(X[0])):
        Z[i][j] = X[i][j] + Y[i][j]

for r in Z:
    print(r)

[17. 15.  4.]
[10. 12.  9.]
[11. 13. 18.]


## Matriz transposta

A matriz transposta inverte linhas e colunas de uma matriz, ou seja dada uma matriz A (nxm) transformamos as linhas de A em colunas, e as colunas de A em linhas.

In [336]:
X = [[12,7],
    [4 ,5],
    [3 ,8]]

X = np.array(X)

X

array([[12,  7],
       [ 4,  5],
       [ 3,  8]])

In [337]:
np.shape(X)

(3, 2)

In [338]:
# usando função transpose do numpy
Xt = np.transpose(X)

Xt

array([[12,  4,  3],
       [ 7,  5,  8]])

In [339]:
np.shape(Xt)

(2, 3)

In [340]:
Xt = np.zeros((2,3))

Xt

# iterando nas linhas
for i in range(len(X)):
    # iterando nas colunas
    for j in range(len(X[0])):
        Xt[j][i] = X[i][j]

for r in Xt:
    print(r)

[12.  4.  3.]
[7. 5. 8.]


## Transpose usando compreensão de listas

In [342]:
X = [[12,7],
    [4 ,5],
    [3 ,8]]

X = np.array(X)

X

array([[12,  7],
       [ 4,  5],
       [ 3,  8]])

In [343]:
X[0]

array([12,  7])

In [344]:
len(X)

3

In [345]:
len(X[0])

2

In [346]:
Xt = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]

for r in Xt:
    print(r)

[12, 4, 3]
[7, 5, 8]


## Multiplicando matrizes

Para que a multiplicação de matrizes seja possível, supondo uma matriz $A_{ij}$, e outra matriz $B_{nm}$, para que a multiplicação de A por B seja possível, é necessário que $j = n$, e o resultado desta multiplicação é uma matriz $C_{im}$.

**Exemplo**

Supondo uma matriz A(2x2), e uma matriz B(2x3), vamos calcular a multiplicação destas duas matrizes

\[A = \begin{pmatrix}1 & 2 \\
3 & 4
\end{pmatrix}
\]

\[B = \begin{pmatrix}
1 & 1 & 2\\
3 & 4 & 1
\end{pmatrix}
\]

O resultado da multiplicação de A por B resulta numa matriz C(2x3)

\[C = \begin{pmatrix}
c_{11} & c_{12} & c_{13}\\
c_{21} & c_{22} & c_{23}
\end{pmatrix}
\]

\[c_{11} = a_{11} * b_{11} + a_{12}*b_{21} = 1*1 + 2*3 = 7\]

\[c_{12} = a_{11} * b_{12} + a_{12}*b_{22} = 1*1 + 2*4 = 9\]

\[c_{13} = a_{11} * b_{13} + a_{12}*b_{23} = 1*2 + 2*1 = 4\]

In [347]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

X = np.array(X)

X

array([[12,  7,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [348]:
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

Y = np.array(Y)

Y

array([[5, 8, 1, 2],
       [6, 7, 3, 0],
       [4, 5, 9, 1]])

In [355]:
np.matmul(X,Y)

array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])

In [356]:
np.matmul(Y,X)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [351]:
n = len(X[0])

n

3

In [352]:
m = len(Y[0])

m

4

In [353]:
# definindo matriz nula/inicializando uma matriz com entradas igual a 0
Z = np.zeros((n,m))

Z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [354]:
# iterando nas colunas de X
for i in range(len(X)):
   # iterando nas colunas de Y
    for j in range(len(Y[0])):
       # iterando nas linhas de Y
        for k in range(len(Y)):
            Z[i][j] += X[i][k] * Y[k][j]

for r in Z:
    print(r)

[114. 160.  60.  27.]
[74. 97. 73. 14.]
[119. 157. 112.  23.]


In [359]:
# usando numpy para multiplicar matrizes
np.matmul(X, Y)

array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])

## Definindo matrizes via for

In [360]:
n,m = 3,3

X = np.zeros((n,m))

X

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [361]:
def f(i,j):
    f = (i+1)*(j+1)
    return f

f(2,3)

12

In [365]:
f(0,0)

1

In [366]:
f(0,1)

2

In [367]:
f(0,2)

3

In [368]:
f(1,0)

2

In [369]:
f(1,1)

4

In [370]:
f(1,2)

6

In [364]:
for i in range(len(X)):
    # iterando nas colunas
    for j in range(len(X[0])):
        X[i][j] = f(i,j)
        
for r in X:
    print(r)

[1. 2. 3.]
[2. 4. 6.]
[3. 6. 9.]


In [371]:
X

array([[1., 2., 3.],
       [2., 4., 6.],
       [3., 6., 9.]])

## Matriz identidade utilizando for aninhado

In [380]:
def f(i,j):
    if i == j:
        return 1
    else:
        return 0

for i in range(len(X)):
    # iterando nas colunas
    for j in range(len(X[0])):
        X[i][j] = f(i,j)
        
for r in X:
    print(r)

[1. 0. 0.]
[0. 1. 0.]
[0. 0. 1.]


## Outro exemplo de matriz por lei de formação

In [389]:
def f(i,j):
    f = i * j
    return f

for i in range(len(X)):
    # iterando nas colunas
    for j in range(len(X[0])):
        X[i][j] = f(i,j)
        
for r in X:
    print(r)

[0. 0. 0.]
[0. 1. 2.]
[0. 2. 4.]


## Soma da diagonal principal

Esta soma da diagonal principal é também conhecida por traço da matriz (quadrada). A diagonal principal são os termos $a_{ii}$ de uma matriz A.

In [390]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

X = np.array(X)

X

array([[12,  7,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [391]:
traco = X[0][0] + X[1][1] + X[2][2]

traco

26

In [392]:
X[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [395]:
X[1,:]

array([4, 5, 6])

In [396]:
X[:,2]

array([3, 6, 9])

In [397]:
soma = 0
traco = 0
for i in range(len(X)):
    traco = traco + X[i][i] 

traco

26

## Matriz de Vandermonde

Em álgebra linear, a matriz de Vandermonde, nomeada por causa de seu descobridor Alexandre-Théophile Vandermonde, é uma matriz cujos termos representam uma progressão geométrica em cada uma de suas linhas (matriz m × n)

\[ V = {\begin{bmatrix}1&x_{1}&x_{1}^{2}&\dots &x_{1}^{n-1}\\1&x_{2}&x_{2}^{2}&\dots &x_{2}^{n-1}\\1&x_{3}&x_{3}^{2}&\dots &x_{3}^{n-1}\\\vdots &\vdots &\vdots &\ddots &\vdots \\1&x_{m}&x_{m}^{2}&\dots &x_{m}^{n-1}\end{bmatrix}}\]

A lei de geração da matriz de Vandermonde é

\[\displaystyle V_{i,j}=x_{i}^{j-1}\]

In [ ]:
def f(n,i,j):
    x = np.array([input(), 2, 3])
    f = i ** (j-1)
    return f

x = np.array()
for i in range(0,n):
    x[i] = input()

for i in range(len(X)):
    # iterando nas colunas
    for j in range(len(X[0])):
        X[i][j] = f(i,j)
        
for r in X:
    print(r)

In [398]:
# 
x = np.array([1, 2, 3])

# grau da matriz de vandermonde
n = 3

# gera matriz de vandermonde
np.vander(x, n)

array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])

In [ ]:
# 
x = np.array([1, 2, 3])

# grau da matriz de vandermonde
n = 4

# gera matriz de vandermonde
np.vander(x, n)

In [ ]:
# 
x = np.array([1, 2, 3, 4, 5])

# grau da matriz de vandermonde
n = 5

# gera matriz de vandermonde
np.vander(x, n)

In [444]:
x = []
n = int(input('n = '))
m = int(input('m = '))

W = np.zeros((m,n))


for i in range(m):
    a = int(input())
    x.append(a)
    
for i in range(m):
    for j in range(n):
        W[i][j] = x[i]**(j)
        
W

n = 5
m = 3
2
3
5


array([[  1.,   2.,   4.,   8.,  16.],
       [  1.,   3.,   9.,  27.,  81.],
       [  1.,   5.,  25., 125., 625.]])

## Matriz circulante

In [448]:
from scipy.linalg import circulant

A = np.array(circulant([1, 2, 3]))

A

array([[1, 3, 2],
       [2, 1, 3],
       [3, 2, 1]])

In [449]:
np.transpose(A)

array([[1, 2, 3],
       [3, 1, 2],
       [2, 3, 1]])

# Desafios

## Desafio Clark

Crie uma função para calcular a soma de uma série de números dada pela seguinte lei de geração

\[S_n(k) = 1^k + 2^k + 3^k + \cdots + n^k\]

A função deve ter como entrada os números n (número natural que varia de 0 até infinito), e o valor de k (número inteiro que varia de menos infinito a mais infinito). A função deve retornar o valor da soma dos primeiros n números naturais dada a potência k, e o tempo de execução da função. Criar um loop for para criar um dataframe para um valor fixo de k (pode escolher k = 1), que contenha o tempo de execução para cada um dos valores de n, e depois plotar a curva tempo vs n. O dataframe deve ter 2 colunas, o valor de n, e o tempo de execução para n, sendo que n pode variar de 1 até infinito. Utilize uma quantidade de pontos suficientes para plotar o gráfico de tempo vs n e perceber padrões no tempo de execução.

## Desafio Luis Felipe

Criar uma função para calcular as raízes de uma equação do segundo grau. A função deve ter como entrada os valores dos coeficientes (a,b,c) da função do segundo grau

\[f(x) = ax^2 + bx + c\]

A função deve retornar: o valor do x do vértice, valor do y do vértice, valor do discriminante, valor das duas raízes, gráfico da função dada pelos coeficientes (a,b,c). A função também deve calcular algebricamente as raízes mesmo em caso de raízes complexas (determinante menor que zero).

## Desafio Felipe

Crie uma função usando laço com for loop para receber como entrada uma matriz quadrada e a função deve retornar o traço da matriz (soma dos termos da diagonal principal), a norma_1 (soma de todos os elementos da matriz), norma_abs (soma dos valores absolutos de todos os termos da matriz), norma_2 (soma dos quadrados de todos os termos da matriz). Crie funções para definir funções das linhas e colunas de uma matriz (i,j) e as utilize para dentro de um laço for criar tipos especiais de matrizes quadradas e retornar os valores da função que retorna os valores calculados do item anterior. Defina as seguintes funções abaixo

1. Matriz de Vandermonde
2. Matriz circulante
3. f(i,j) = 1 se i for igual a j, e f(i,j) = 0 caso contrário
4. f(i,j) = (i+1)^(j+1)
5. f(i,j) = (i+1)*(j+1)